apiVersion: v1
kind: ConfigMap
metadata:
  name: micropet-service-$(workload.metadata.name)$-config     
data:
  values.yml: |  
    application:
      name: micro-pet-3
    service:  
      name: cats
      port: 7002
      image: harbor.mytanzu.xyz/library/micropet-tap-cats@sha256:7c23f63dff382380985b870e20b2dae06fdcd61651e40ad1c78616abdf3ee81f
      replicas: 1
      backend:
        observability: false
        mode: RANDOM_NUMBER
        frequencyError: 10
    environment:
      name: aws/europ
      ingress: contour
      domain:
        internal: .micropets-supplychain.svc.cluster.local
        exposed: front.mytanzu.xyz


